Update ReadME
vtex-apps/reviews-and-ratings pull request #121
Opened 2021-12-01 20:55 UTC by aurorahey

This PR is for triggering the automatically publish the new version, and updating the README file for the new feature

2021-12-01 21:01 UTC, polishq commented on docs/README.md
> +4. You can export reviews to xls files from the **Download** tap, and it is limited to exporting 800 reviews. Please use the date pickers to select the time range of reviews you want to export.
```suggestion
4. You can export reviews to XLS files from the **Download** tab, and it is limited to exporting 800 reviews at a time. Please use the date pickers to select the time range of reviews you want to export.
```

2021-12-01 21:07 UTC, polishq approved these changes

2021-12-01 21:28 UTC, Mariana-Caetano requested changes
LGTM @aurorahey! I've just added a suggestion in terms of editing style.

2021-12-01 21:28 UTC, Mariana-Caetano commented on docs/README.md
> +4. You can export reviews to XLS files from the **Download** tab, and it is limited to exporting 800 reviews at a time. Please use the date pickers to select the time range of reviews you want to exp
```suggestion
> ⚠️ Warning
>
> You can export reviews to XLS files from the **Download** tab, and it is limited to exporting 800 reviews at a time. Please use the date pickers to select the time range of reviews you want to export.
```

2021-12-02 11:28 UTC, camilavcoutinho approved these changes

2021-12-02 13:08 UTC, Mariana-Caetano approved these changes

2021-12-02 14:11 UTC, polishq approved these changes

2021-12-02 14:14 UTC, merged