Feature/reviews 33 rating filter
vtex-apps/reviews-and-ratings pull request #137
Opened 2021-12-20 18:01 UTC by aurorahey

#### What problem is this solving?

#### How to test it?

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2021-12-20 18:05 UTC, camilavcoutinho submitted a review, later dismissed

2021-12-21 21:40 UTC, polishq requested changes

2021-12-21 21:40 UTC, polishq commented on dotnet/Services/ProductReviewService.cs
> +            if (rating == 1 || rating == 2 || rating == 3 || rating == 4 || rating == 5)
```suggestion
            if (rating > 0 && rating <= 5)
```

2021-12-21 21:40 UTC, polishq commented on react/Reviews.tsx
> +      value: '0',
Why not make these values integers instead of strings?

2021-12-23 17:00 UTC, closed without merging