Fix/reviews 38 fix verify schema process
vtex-apps/reviews-and-ratings pull request #140
Opened 2022-01-12 21:03 UTC by Arturo777

Workspace to test: https://arturoreviews--sandboxusdev.myvtex.com/reviews-and-ratings/verify-schema

How to test:
Change the schema stored in both vBase and MD via postman, log into the account and run the Verify Schema endpoint.

2022-01-12 21:30 UTC, btalma submitted a review, later dismissed
I recommend creating a constant for `HashedSchema`

2022-01-13 15:12 UTC, btalma submitted a review, later dismissed

2022-01-13 15:18 UTC, Arturo777 commented
> 

Ok, the constant was created, thanks!

2022-01-13 16:01 UTC, aurorahey approved these changes

2022-01-13 16:03 UTC, polishq requested changes

2022-01-14 20:32 UTC, merged