[REVIEWS-70] fix validation alerts
vtex-apps/reviews-and-ratings pull request #158
Opened 2022-03-03 21:00 UTC by aurorahey

#### What problem is this solving?

Fix the ValidateKeyAndToken function alerts, added retry and maximum retry is 5 times

2022-03-03 21:25 UTC, btalma submitted a review, later dismissed

2022-03-04 16:10 UTC, polishq requested changes

2022-03-04 16:10 UTC, polishq commented on dotnet/DataSources/ProductReviewRepository.cs
> +                        _context.Vtex.Logger.Error("ValidateKeyAndToken", null, $"Error validating key and token '{key}'", ex);
```suggestion
                        _context.Vtex.Logger.Warn("ValidateKeyAndToken", null, $"Error validating key and token '{key}'", ex);
```

2022-03-04 16:10 UTC, polishq commented on dotnet/DataSources/ProductReviewRepository.cs
> +                        if (++count == max) throw ex;
```suggestion
                        if (++count == max)
                        {
                         _context.Vtex.Logger.Error("ValidateKeyAndToken", null, $"Maximum retries reached validating key and token '{key}'", ex);
                         throw ex;
                        }
```

2022-03-04 16:31 UTC, polishq submitted a review, later dismissed

2022-03-04 16:57 UTC, polishq approved these changes

2022-03-04 16:58 UTC, merged