[REVIEWS-107] Translate migrate data button.
vtex-apps/reviews-and-ratings pull request #201
Opened 2022-07-13 19:19 UTC by Arturo777

#### What problem is this solving?

As simple as translating the Migrate Data button.

### Screenshots
![Screen Shot 2022-07-13 at 13 35 12](https://user-images.githubusercontent.com/49737670/178814228-c2b86ea3-6107-41fb-9000-048e69c63ede.png)
![Screen Shot 2022-07-13 at 13 34 59](https://user-images.githubusercontent.com/49737670/178814230-be6897aa-482a-4a2a-90bf-97748b33aec1.png)

![Screen Shot 2022-07-13 at 13 35 27](https://user-images.githubusercontent.com/49737670/178814218-aa912392-7855-49c3-abe5-3b2bdbb98754.png)

2022-07-13 19:45 UTC, wender approved these changes

2022-07-14 13:01 UTC, btalma approved these changes
LGTM

2022-07-22 19:58 UTC, camilavcoutinho requested changes

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/bg-BG.json
> +  "admin/reviews.migrateData": "мигриране на данни",
```suggestion
  "admin/reviews.migrateData": "Прехвърляне на данните",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/es.json
> +  "admin/reviews.migrateData": "Migrar Datos",
```suggestion
  "admin/reviews.migrateData": "Migrar datos",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/fr-FR.json
> +  "admin/reviews.migrateData": "Migrer Des Données",
```suggestion
  "admin/reviews.migrateData": "Transférer les données",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/it-IT.json
> +  "admin/reviews.migrateData": "Migrare i Dati",
```suggestion
  "admin/reviews.migrateData": "Migra dati",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/ja-JP.json
> +  "admin/reviews.migrateData": "データの移行",
```suggestion
  "admin/reviews.migrateData": "データを移行",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/ko-KR.json
> +  "admin/reviews.migrateData": "데이터 마이그레이션",
```suggestion
  "admin/reviews.migrateData": "데이터 이전",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/nl-NL.json
> +  "admin/reviews.migrateData": "Gegevens Migreren",
```suggestion
  "admin/reviews.migrateData": "Gegevens migreren",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/pt.json
> +  "admin/reviews.migrateData": "Migrar Dados",
```suggestion
  "admin/reviews.migrateData": "Migrar dados",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/ro-RO.json
> +  "admin/reviews.migrateData": "Migrați Datele",
```suggestion
  "admin/reviews.migrateData": "Migrează date",
```

2022-07-22 19:58 UTC, camilavcoutinho commented on messages/th-TH.json
> +  "admin/reviews.migrateData": "ย้ายข้อมูล",
```suggestion
  "admin/reviews.migrateData": "ย้ายข้อมูล",
```

2022-07-25 12:20 UTC, camilavcoutinho approved these changes

2022-07-25 15:05 UTC, whc105 approved these changes
LGTM

2022-07-25 15:06 UTC, merged