Translating ShowMore component to portuguese
vtex-apps/reviews-and-ratings pull request #251
Opened 2023-07-17 19:44 UTC by renatoricardi

#### What problem is this solving?
There are some "buttons" that show texts in English instead of the region itself.

#### How to test it?
[Workspace](https://aa254--lojausereserva.myvtex.com/camiseta-estampada-r-pica-pau-class0071847/p)

#### Screenshots or example usage:
![image](https://github.com/vtex-apps/reviews-and-ratings/assets/88559746/f95d09f9-ae1d-4df2-8b03-f031f9e261ac)
![image](https://github.com/vtex-apps/reviews-and-ratings/assets/88559746/c474bec6-719b-4a6b-9e8f-e17f122aab42)

2023-07-17 20:33 UTC, beatrizmaselli approved these changes
LGTM

2023-07-17 20:56 UTC, beatrizmaselli requested changes
Add `en.json` static messages and remove defaultMessage

2023-07-20 20:44 UTC, Mecrano commented
LGTM

2023-07-20 20:44 UTC, Mecrano approved these changes
LGTM

2023-07-21 16:36 UTC, camilavcoutinho requested changes

2023-07-21 16:36 UTC, camilavcoutinho commented on messages/en.json
> +  "store/reviews.list.showLess": "Show Less"
```suggestion
  "store/reviews.list.showMore": "Show more",
  "store/reviews.list.showLess": "Show less"
```

2023-07-21 16:42 UTC, camilavcoutinho approved these changes

2023-07-24 15:37 UTC, beatrizmaselli approved these changes
LGTM

2023-07-26 14:12 UTC, beatrizmaselli approved these changes

2023-08-09 12:11 UTC, merged