Css handlers
vtex-apps/reviews-and-ratings pull request #33
Opened 2020-09-20 16:17 UTC by khrizzcristian

Added 7 more css handlers

2020-09-21 10:03 UTC, khrizzcristian commented
What is wrong with my pull request? I can't find any issue in my code but I found in Lint this kind of errors

##[error]  496:18  error    Replace `·className={`${handles.reviewsRatingAverage}·review__rating--average·dib·v-mid`}` with `⏎··············className={`${handles.reviewsRatingAverage}·review__rating--average·dib·v-mid`}⏎············`                                                                prettier/prettier
##[error]  504:18  error    Replace `·className={`${handles.reviewsRatingCount}·review__rating--count·dib·v-mid`}` with `⏎··············className={`${handles.reviewsRatingCount}·review__rating--count·dib·v-mid`}⏎············`                                                                        prettier/prettier
##[error]  597:27  error    Replace `·className={`${handles.reviewCommentRating}·review__comment--rating·t-heading-5`}` with `⏎························className={`${handles.reviewCommentRating}·review__comment--rating·t-heading-5`}⏎······················`                                          prettier/prettier
##[error]  599:30  error    Replace `·className={`${handles.reviewCommentUser}·review__comment--user·lh-copy·mw9·t-heading-5·mt0·mb2`}` with `⏎··························className={`${handles.reviewCommentUser}·review__comment--user·lh-copy·mw9·t-heading-5·mt0·mb2`}⏎························`      prettier/prettier
##[error]  639:29  error    Replace `·className={`${handles.reviewCommentRating}·review__comment--rating·t-heading-5`}` with `⏎··························className={`${handles.reviewCommentRating}·review__comment--rating·t-heading-5`}⏎························`                                      prettier/prettier
##[error]  641:32  error    Replace `·className={`${handles.reviewCommentUser}·review__comment--user·lh-copy·mw9·t-heading-5·mt0·mb2`}` with `⏎····························className={`${handles.reviewCommentUser}·review__comment--user·lh-copy·mw9·t-heading-5·mt0·mb2`}⏎··························`  prettier/prettier

2020-09-21 14:42 UTC, klzns requested changes

2020-09-21 14:42 UTC, klzns commented on docs/README.md
> +| 'reviewCommentUser'       |
It's better to keep the list sorted and with code formatting. Also some existing CSS Handles are missing.

```suggestion
| `container`               |
| `loginLink`               |
| `reviewComment`           |
| `reviewCommentRating`     |
| `reviewCommentsContainer` |
| `reviewCommentUser`       |
| `reviewsHeading`          |
| `reviewsRating`           |
| `reviewsRatingAverage`    |
| `reviewsRatingCount`      |
| `star--empty`             |
| `star--filled`            |
| `star`                    |
| `starpicker`              |
| `starsContainer`          |
| `writeReviewContainer`    |
```

2020-09-21 14:42 UTC, klzns commented on react/Reviews.tsx
> +  'reviewCommentUser'
Missing trailing comma `,`

2020-09-21 14:42 UTC, klzns commented on react/Reviews.tsx
> +            <span className={`${handles.reviewsRatingAverage} review__rating--average dib v-mid`}>
Lint issue here (reported by the GitHub Action)

To setup the linter you should run:
-  `yarn` on the root directory
-  `yarn` on the `react` directory

Then run `yarn lint --fix` on the root directory to fix the issues.

2020-09-21 15:16 UTC, guerreirobeatriz requested changes

2020-09-21 15:16 UTC, guerreirobeatriz commented on docs/README.md
> +| 'reviewCommentUser'       |
```suggestion
| 'container'               |
| 'loginLink'               |
| 'reviewComment'           |
| 'reviewCommentsContainer' |
| 'reviewCommentRating'     |
| 'reviewCommentUser'       |
| 'reviewsHeading'          |
| 'reviewsRating'           |
| 'reviewsRatingAverage'    |
| 'reviewsRatingCount'      |
| 'starsContainer'          |
| 'writeReviewContainer'    |
```

2020-09-22 09:18 UTC, khrizzcristian commented
How can I fix that Danger CI error?

2020-09-22 13:50 UTC, klzns requested changes
The Danger CI is complaining about a missing entry in the CHANGELOG.md

You can add something like this under the [Unreleased] section of the file:

```diff
 ## [Unreleased]

+### Added
+- Missing CSS Handles
```

2020-09-22 13:50 UTC, klzns commented on docs/README.md
>  | `container`               |
```suggestion
| `container`               |
| `formContainer`           |
```

2020-09-22 13:50 UTC, klzns commented on docs/README.md
> +| `starsContainer`          |
```suggestion
| `stars`                   |
| `starsContainer`          |
| `summaryContainer`        |
```

2020-09-22 14:02 UTC, klzns approved these changes

2020-09-22 18:23 UTC, guerreirobeatriz approved these changes

2020-09-28 16:32 UTC, khrizzcristian commented
Hello. Cam anyone metge my pull request?
Thank you

2020-09-30 17:08 UTC, merged

2020-09-30 17:21 UTC, klzns commented
@allcontributors add @khrizzcristian for code

2020-10-01 07:08 UTC, khrizzcristian commented
Hello. I can't deploy the changes
10:07:16.905 - error: Role User:cristian.longo@customsoft.ro in vtex/
cannot perform action PATCH on resource
vrn:apps:aws-us-east-1:vtex:master:/registry/vtex.reviews-and-ratings/2.1.0

*------------------*
*Cristian Longo*
*Web Developer*



On Wed, 30 Sep 2020 at 20:08, vtex-io-ci-cd[bot] <notifications@github.com>
wrote:

> Your PR has been merged! App is being published. 🚀
> *Version 2.0.3 → 2.1.0*
>
> After the publishing process has been completed (check #vtex-io-releases
> <https://vtex.slack.com/archives/CT98SSTU4>) and doing A/B tests with the
> new version, you can deploy your release by running:
>
> vtex deploy vtex.reviews-and-ratings@2.1.0
>
> After that your app will be updated on all accounts.
>
> For more information on the deployment process check the docs
> <https://vtex.io/docs/releases/2019-week-47-48-49-50-51/publish-command>.
> 📖
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vtex-apps/reviews-and-ratings/pull/33#issuecomment-701522670>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKL3X6F4MIQSFPRA5QFM2ALSINQYRANCNFSM4RTW5NVQ>
> .
>