Feature/api
vtex-apps/reviews-and-ratings pull request #54
Opened 2021-01-22 13:21 UTC by btalma

#### What problem is this solving?

Added API

#### How to test it?

Linked at https://rar--sandboxusdev.myvtex.com
See documentation PDF for methods

#### Screenshots or example usage:

curl --location --request POST 'https://rar--sandboxusdev.myvtex.com/reviews-and-ratings/api/review' \
--header 'VtexIdclientAutCookie: eyJhbGciOiJFUzI1NiIsImtpZCI6IkM5NDI3NkQ1RTE0MTRBREM3RDA2RDYzRUM1RjFGNkExRkIzOTQ2MzIiLCJ0eXAiOiJqd3QifQ.eyJzdWIiOiJicmlhbi50YWxtYUB2dGV4LmNvbS5iciIsImFjY291bnQiOiJzYW5kYm94dXNkZXYiLCJhdWRpZW5jZSI6ImFkbWluIiwic2VzcyI6IjkxYjM4NDM5LTgxZWYtNDA2Mi1hMTMyLTU0NThmMTM4ZjE1ZCIsImV4cCI6MTYxMTMzMjA1OCwidXNlcklkIjoiZjg3MDczZjAtODI0MC00OTQyLWI2N2UtYjM3ZDkwMWQ3YTdjIiwiaWF0IjoxNjExMjQ1NjU4LCJpc3MiOiJ0b2tlbi1lbWl0dGVyIiwianRpIjoiNmUwYzAwNzctZThlOS00NzFmLTg2NTctMWQzNmNmN2ExZGFkIn0.EaSK9kmqmUgp_yRE-oaQs6Qki6RziQ86Z_Rm3Pq5AqBJcOUizY1ihWv0EEyz3vr_k0B-8Nz2aalwRJojJgrv5A' \
--header 'Content-Type: application/json' \
--data-raw '{
    "ProductId": "23",
    "Rating": 2,
    "Text": "It'\''s okay."
}'

2021-01-22 14:27 UTC, SDBowen approved these changes

2021-01-22 14:50 UTC, klzns requested changes
Remove commented code and console.writeline

2021-01-22 15:59 UTC, klzns approved these changes

2021-01-27 21:56 UTC, carolinamenezes approved these changes

2021-01-27 21:58 UTC, merged