New Crowdin updates
vtex-apps/reviews-and-ratings pull request #85
Opened 2021-07-02 20:19 UTC by daniserejo

2021-08-23 17:50 UTC, wender requested changes
Missing CHANGELOG file

2021-08-24 13:54 UTC, camilavcoutinho reviewed
@daniserejo you need to delete ach-UG.json and pt-BR.json

2021-08-24 16:41 UTC, camilavcoutinho requested changes

2021-08-24 16:41 UTC, camilavcoutinho commented on CHANGELOG.md
> +- I18n bs-BA
```suggestion
- I18n pseudo language to implement In Context tool.
```

2021-08-30 18:44 UTC, camilavcoutinho commented
@daniserejo could you rebase? there is a conflict in the changelog

2021-08-31 17:11 UTC, camilavcoutinho commented
@daniserejo this PR needs rebase and the deletion of pt-BR.json, please 😊

2021-09-16 19:53 UTC, wender approved these changes

2021-09-16 20:10 UTC, igorbrasileiro approved these changes

2021-09-16 20:10 UTC, camilavcoutinho approved these changes

2021-09-16 20:40 UTC, merged